name: myownapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/EMERGENCY.jpg
    - assets/images/HOMEPAGE.jpg
    - assets/images/KOLKATA.jpg


    - assets/images/MUMBAI.jpg
    - assets/images/DELHI.jpg

    - assets/images/JAIPUR.jpg
    - assets/images/PUNE.jpg
    - assets/images/BENGALURU.jpg
    - assets/images/MUMBAIE.jpg
    - assets/images/DELHIE.jpg

    - assets/images/JAIPURE.jpg
    - assets/images/PUNEE.jpg
    - assets/images/BENGALURUE.jpg
    - assets/images/KOLKATAE.jpg
    - assets/images/MUMBAIL.jpg
    - assets/images/DELHIL.jpg


    - assets/images/KOLKATAL.jpg
    - assets/images/historykol.jpg
    - assets/images/kolkatacult.jpg
    - assets/images/bengalurucult.jpg
    - assets/images/bengaluruhist.jpg
    - assets/images/mumbaicult.jpg
    - assets/images/mumbaihist.jpg

    - assets/images/delhicult.jpg
    - assets/images/delhihist.jpg
    - assets/images/jaipurcult.jpg
    - assets/images/jaipurhist.jpg
    - assets/images/punecult.jpg
    - assets/images/punehist.jpg
    - assets/images/victoria.jpg
    - assets/images/belur.jpg
    - assets/images/sciencecity.jpg
    - assets/images/CUISINE.jpg
    - assets/images/TOUR.jpg
    - assets/images/belur.jpg
    - assets/images/bnp.jpg
    - assets/images/bg.jpg
    - assets/images/bp.jpg
    - assets/images/kc.jpg
    - assets/images/lt.jpg
    - assets/images/cb.jpg
    - assets/images/agp.jpg
    - assets/images/sp.jpg
    - assets/images/md.jpg
    - assets/images/ec.jpg
    - assets/images/ig.jpg
    - assets/images/cp.jpg
    - assets/images/HYDERABADL.jpg
    - assets/images/jmj.jpg
    - assets/images/nf.jpg
    - assets/images/gf.jpg
    - assets/images/jm.jpg
    - assets/images/qm.jpg
    - assets/images/kulfi.jpg
    - assets/images/roshogollas.jpg
    - assets/images/golgappa.jpg
    - assets/images/vada.jpg
    - assets/images/mawacake.jpg
    - assets/images/keemapav.jpg
    - assets/images/jhalmuri.jpg
    - assets/images/bsandwich.jpg
    - assets/images/pkk.jpg
    - assets/images/dbc.jpg
    - assets/images/hb.jpg
    - assets/images/h.jpg
    - assets/images/indiaflag.jpg
    - assets/images/mb.jpg
    - assets/images/db.jpg
    - assets/images/indiahist.jpg
    - assets/images/indiacult.jpeg
    - assets/images/indiafact.jpeg

















        # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

